name: Merge to Develop Jobs

on:
  push:
    branches:
      - develop

jobs:
  Execute-Test:
    uses: my-motivational-quotes/lib-github-actions/.github/workflows/job-execute-tests.yaml@main
  Bump-Version:
    needs: [Execute-Test]
    uses: my-motivational-quotes/lib-github-actions/.github/workflows/job-bump-version.yaml@main
    with:
      artifact_name: svc-client
      version: minor
    secrets:
      access_token: ${{ secrets.ACCESS_TOKEN }}
